### ISSUE TITLE
PlayerEventProducer does not properly handle AVPlayerItemDidPlayToEndTime

### ISSUE THREAD

**Issue by samutay** [delannoyk/AudioPlayer#77] opened 2016-11-10 04:14 UTC
The addObserver passes the player as the object but should be the player.currentItem. According to the docs, the observed object must be the AVPlayerItem instance, not the AVPlayer itself. So this event does not fire in the newest code.

e.g. line 129 should be
center.addObserver(self, selector: .itemDidEnd, name: .AVPlayerItemDidPlayToEndTime, object: player.currentItem)

**Comment by samutay** [comment] 2016-11-10 04:44
Actually, probably needs better refactoring and moving that event to AudioItemEventProducer since it is associated with the AudioItem.

**Comment by JeanetteMueller** [comment] 2016-11-16 14:17
Thank you very much. I have already been looking for the error

**Comment by danielmartinprieto** [comment] 2016-11-22 16:22
I've been able to reproduce this issue. As a workaround I guess you can check in the AudioPlayerDelegate method `audioPlayer(_ audioPlayer: AudioPlayer, didUpdateProgressionTo time: TimeInterval, percentageRead: Float)` if the percentage is 100.

**Comment by danielmartinprieto** [comment] 2016-11-23 21:30
My workaround doesn't seem to work, and indeed changing `center.addObserver(self, selector: .itemDidEnd, name: .AVPlayerItemDidPlayToEndTime, object: player)` by `center.addObserver(self, selector: .itemDidEnd, name: .AVPlayerItemDidPlayToEndTime, object: player.currentItem)` seems to do it.

**Comment by delannoyk** [comment] 2016-11-24 00:16
Yep that's an error. Fixing that right now.
It's not part of `AudioItemEventProducer` because that one is used for pure `AudioItem` changes, not the `AVFoundation` part.

**Comment by delannoyk** [comment] 2016-11-24 00:17
Thanks for the report. Fixed on master.

**Closed by delannoyk** 2016-11-24 00:17 UTC
