### ISSUE TITLE
Sometimes playback is automatically paused

### ISSUE THREAD

**Issue by han9over** [delannoyk/AudioPlayer#37] opened 2016-03-01 23:04 UTC
Playback is getting paused automatically without any interruptions or any actions. The network connectivity is good and the playback has to be manually resumed by hitting play again.

Observed this happening with recent updates.

**Comment by delannoyk** [comment] 2016-03-10 17:59
Hi there,
I haven't experienced this bug although I'm not yet using latest release in production. Does this happen randomly or is there a way to reproduce? Do you play livetreams?
If you have more information you care to share, let me know :)

**Comment by han9over** [comment] 2016-03-10 18:12
Thanks for your response. I tried to reproduce this, but was unable to. I'm using remote MP3 Urls for playing this.

I know that using below method is not correct, but I'm trying to test the issue. So, I used a youtube audio url and it just throws error saying The operation cannot be completed. But, the same thing works fine when I instantiate AVPlayer..

**Comment by delannoyk** [comment] 2016-03-10 18:33
This is interesting although unrelated to this issue. Would you mind creating a separated one? I want to look into it :)

**Comment by han9over** [comment] 2016-03-10 18:36
Will do. I will try to use a youtube URL and replicate the issue and document those. Thanks.

**Comment by delannoyk** [comment] 2016-03-10 18:48
What kind of Youtube's URL do you use? I just tried to get an URL to a YouTube's mp4 (containing video) and it worked out of the box.

**Comment by han9over** [comment] 2016-03-10 18:51
i'm using a mp4 audio link. I don't have access from work, but the process I did for testing is,

I took a youtube song url, then went to www.clipconverter.cc and then used firebug or http packet tool for sniffing network traffic.

then when you enter youtube url in that site and hit enter or something it sends request to grab youtube urls. You can see the JSON response and it will have urls in it.

you can take any URL and it will have 2 links in it concatenated together by #audio= something like that.

the url after #audio= is the audio url for that resolution of video :)

**Comment by han9over** [comment] 2016-03-10 18:53
if you want to test that url, you can paste that url in safari and it will play automatically if the song link is correct. Safari kicks off AVPlayer and if that can be played in safari, it should work in this library too.. technically :)

**Comment by delannoyk** [comment] 2016-03-10 19:20
That is what I did and it worked

**Comment by delannoyk** [comment] 2016-03-10 19:24
Also, it worked with the video URL.

**Comment by han9over** [comment] 2016-03-10 19:25
that's weird.. let me try tonight and i will get back to you with the video that it didn't work. May be its only related to the videos i'm using :)

**Comment by han9over** [comment] 2016-03-11 01:00
Here is a song I tried.. Just a random pick :) 

https://www.youtube.com/watch?v=8B29SZvMi3E

Here is the audio URL that i received. This might expire by the time you check.

https://r8---sn-4g57knkl.googlevideo.com/videoplayback?id=o-AIvdELTMN9fvcZsV8e-a7CSDfl_piJZ_izysVXrkqIdF&pl=23&signature=6DE6D58CE64B3E93A67F6A9D5AADAE90B6B45815.4AB0EBA7EB63936A9685391FC27C2C8E157499C4&ipbits=0&key=cms1&ip=37.59.142.11&gir=yes&fexp=9406993,9416126,9420452,9422596,9423661,9423662,9425397,9428243,9428605,9429122,9429131,9429237,9430941,9431117&dur=263.058&sparams=clen,dur,expire,gir,id,initcwndbps,ip,ipbits,itag,keepalive,lmt,mime,mm,mn,ms,mv,nh,pl,requiressl,source,upn&requiressl=yes&expire=1457679383&mime=audio/mp4&itag=140&sver=3&clen=4224031&source=youtube&upn=1EHRhk_Nwf0&keepalive=yes&lmt=1411540153995309&ratebypass=yes&redirect_counter=1&req_id=aa7d376bf6f3a3ee&cms_redirect=yes&mm=34&mn=sn-4g57knkl&ms=ltu&mt=1457657860&mv=m&nh=IgpwcjAyLmZyYTE1KgkxMjcuMC4wLjE#audiosize=4224031

Error I got:
didChangeStateFrom error : Optional(Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSUnderlyingError=0x7fa4f35db4c0 {Error Domain=NSOSStatusErrorDomain Code=-12936 "(null)"}, NSLocalizedFailureReason=An unknown error occurred (-12936), NSLocalizedDescription=The operation could not be completed})

**Comment by han9over** [comment] 2016-03-11 04:14
I did lot of research and found something messed up with my current setup. I created new Xcode project and tried above urls and they worked fine. I reimported my code and processes to this version and so far it seems good. Something might have messed up with other setup. I will do more testing and report if there are any issues.

I think you can close this for now :) thanks for your help and sorry for the trouble .. you rock

**Comment by delannoyk** [comment] 2016-03-11 08:08
Let me know if I can help.
I'm going to close this issue for now, since I haven't been able to reproduce at all. If you could come back in this thread if you have more information/it happens again, I would be grateful!
Thanks.

**Closed by delannoyk** 2016-03-11 08:08 UTC
