### ISSUE TITLE
Playback resumes even if explicitely paused once network is reachable

### ISSUE THREAD

**Issue by PhilippeBridant** [delannoyk/AudioPlayer#24] opened 2015-12-25 15:39 UTC
Hello

Thanks for your great player.

I've found a bug that resumes the playback when network is back reachable even if I paused it before that.

```
 if !pausedForInterruption && state != .Paused && (stateWhenConnectionLost == nil || stateWhenConnectionLost != .Paused) {
    state = .Playing
    player.play()
} else {
    state = .Paused
}
```

This code snippet extracted from AudioPlayer.swift is called when the player has enough data to start the playback again. However, this does not mean that playback has to be restarted.

If I pause my player, then put my app background, go to wifi settings, disable wifi, re-enable it and put my app foreground, the player received a "currentItem.playbackBufferEmpty". The result is that the state variable is changed to  .Buffering and player looses the information that player was paused.

Once it receives "currentItem.playbackLikelyToKeepUp" or "currentProgressionUpdated" event, it finds that:
- playback was not paused for interruption
- state is not paused (because it is buffering)
- state when connection was lost has not been set.

So it sets the state to .Playing and resumes playback.

I dirty patched my copy of the source code with a "should_play" variable set to true or false at appropriate time to know if playback has to be started once network gets back and it seems to work.

I don't know if I am missing something or if I'm right so I prefered creating an issue rather than doing a pull request.

Again, thank for you great player.

Regards

**Comment by PhilippeBridant** [comment] 2015-12-25 15:39
Note that I did not succeed to produce this bug with the simulator.

**Comment by delannoyk** [comment] 2015-12-27 13:19
Hi Philippe,

Thanks for the precision of the issue. I'm looking into it right now.

**Comment by delannoyk** [comment] 2015-12-27 13:36
Couldn't reproduce it on my device but I've pushed a fix to `develop`. Can I ask you to take a look at it?

**Comment by PhilippeBridant** [comment] 2015-12-27 16:56
Thanks. I'll test it right now.

Maybe you should look at my (dirty) commit on my fork: https://github.com/Findspire/AudioPlayer/commit/943b2f38842e359c1dc7c63f6fe51e2807dd6e85

The problem also exists on currentProgressionUpdated event that does a play() because 'state' was set to .Buffering before it was saved on 'stateWhenConnectionLost'.

**Comment by PhilippeBridant** [comment] 2015-12-28 08:13
I confirm that the issue is solved. Except maybe the 'stateWhenConnectionLost' thing.

**Closed** 2016-01-01 09:28 UTC
